# -*- coding: utf-8 -*-
"""almunos menu v2.0

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cIWHWT7-yWUFZurDYCiJ14FzAm9lih8e
"""

ficha={
    'nombre': input('Ingresa tu nombre: '),
    'telefono': int(input('Ingresa tu numero: ')),
    'email': input('Ingresa tu email: ').lower().replace(" ",""),
    'edad': int(input('Ingresa tu edad: '))

}
while True :
  print('=== MENU ===')
  try:
    ocp=int(input('[1]Ver ficha[2]Editar dato[3]Salir'))
  except ValueError:
    print('Error: tiene que ser un numero')
    continue
  if ocp == 1:
    print('==== FICHA ====')
    print('Nombre  :',ficha['nombre'])
    print('Telefono:',ficha['telefono'])
    print('Email   :',ficha['email'])
    print('Edad    :',ficha['edad'])
  elif ocp == 2:
    try:
      editar=input('Ingresa el campo que desea editar: ').lower().replace(" ","")
    except:
      print('Error!!!Tiene que ser una palabra')
      break
    if editar == 'nombre':
      try:
        cambio=input('Ingresa el nombre nuevo: ')
      except:
        print('Error!!!Tiene que ser una palabra')
        break
      ficha['nombre']=cambio

    elif editar == 'telefono':
      try:
        cambio=int(input('Ingresa el nombre nuevo: '))
      except ValueError:
        print('Error!!!Tienes que ingresar un numero')
        break
      ficha['telefono']=cambio
    elif editar == 'email':
      try:
       cambio=input('Ingresa el nombre nuevo: ')
      except:
        print('Error!!!Tiene que ser una palabra')
        break
      ficha['email']=cambio
    elif editar == 'edad':
      try:
        cambio=int(input('Ingresa el nombre nuevo: '))
      except ValueError:
        print('Error!!!Tienes que ingresar un numero')
        break
      ficha['edad']=cambio
  elif ocp == 3:
    print('==== Saliendo del sistema ====')
    break
  else:
    print('Opcion invalida')