# -*- coding: utf-8 -*-
"""ejercicos con listas

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sWmThlTxoget9jbEU1pQ4r3XmqrREWxR
"""

def saludar_alumno() :
  print('Hola alumnos bienvenido al curso')

saludar_alumno()

def obtener_año_actual():
  año = 2026
  nombre ='sergio'
  edad = 20
  return edad

print(obtener_año_actual())

nombre=input('Ingresa tu nombre: ')
nota= float(input('Ingresa tu nota'))

def mostra_estado(nombre,nota):

  if nota>=4.0:
    estado='aprobo el ramo'
  else:
    estado='reprobo el ramo'

  print('estado:',estado)

mostra_estado(nombre, nota)

def calcular_promedio(notas):
  total=sum(notas)
  prom= total/len(notas)
  return round(prom,1)

notas_ana= [6.5,5.8,7.0]
prom_ana= calcular_promedio(notas_ana)
print(f'Promedio: {prom_ana}')

def mostra_menu():
  print('[1]C -> F')
  print('[2]F -> C')
  print('[3]Salir')

mostra_menu()

def pedir_temperatura():
  temperatura=int(input('Ingresa la temperatura '))
  return temperatura

pedir_temperatura()

def mostra_resultado(orig,conv,ud):
  print(orig)
  print(conv)
  print(ud)

mostra_resultado(3.0,40,'CF')

c=float(input('Ingresa la temperatura: '))
def celsius_a_fahrenheit(c):

  return c*9/5 +32

celsius_a_fahrenheit(c)

f=float(input('Ingresa la temperatuta: '))
def fa_a_cel(f):
  return (f-32)*5/9

fa_a_cel(f)